---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: team-one
spec:
  limits:
  - default:
      cpu: 100m
      memory: 64Mi
    defaultRequest:
      cpu: 100m
      memory: 64Mi
    max:
      cpu: 1
      memory: 1Gi
    min:
      cpu: 100m
      memory: 64Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-quota
  namespace: team-one
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 4Gi
    limits.cpu: 4000m
    limits.memory: 4Gi
