apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: db
  labels:
    app: db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data/mysql22"
