apiVersion: v1
kind: ConfigMap
metadata:
  name: librespeed-env
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
data:
  ENABLE_ID_OBFUSCATION: "true"
  TELEMETRY: "true"
  REDACT_IP_ADDRESSES: "false"
  TITLE: RebrainCourceOfKubernetes
  MODE: frontend
  DB_TYPE: mysql
  DB_USERNAME: myuser
  DB_HOSTNAME: "mysql.db.svc.cluster.local"
  DB_NAME: mydatabase
  DB_PORT: "3306"

