apiVersion: v1
kind: Secret
metadata:
  name: librespeed-secret
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  DB_PASSWORD: MTExMTE=
